"use client";

import { useMemo, useState } from "react";
import {
  MOCK_CAMPAIGN_OPTIONS,
  MOCK_CREATIVES,
  MOCK_CREATIVE_STATS,
  MOCK_CREATIVE_STYLES,
} from "@/lib/mock/creatives.mock";
import { AIInlineActionButton } from "@/components/ai-companion/ai-inline-action-button";
import { PageActions } from "@/components/pages/page-actions";
import { FilterChips } from "@/components/ui/filter-chips";
import { Modal } from "@/components/ui/modal";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { formatCurrency, formatNumber, formatPercent } from "@/lib/utils";
import type { CreativeAsset, CreativeFormat } from "@/types";

function statusBadge(status: CreativeAsset["status"]) {
  if (status === "top_performer") return <Badge variant="success">Top Performer</Badge>;
  if (status === "fatigued") return <Badge variant="warning">Fatigued</Badge>;
  if (status === "paused") return <Badge variant="muted">Paused</Badge>;
  return <Badge variant="default">Active</Badge>;
}

export function CreativesPage() {
  const [formatFilter, setFormatFilter] = useState("All");
  const [statusFilter, setStatusFilter] = useState("All");
  const [sort, setSort] = useState("ROAS");
  const [modalOpen, setModalOpen] = useState(false);

  const filtered = useMemo(() => {
    let rows = [...MOCK_CREATIVES];
    if (formatFilter !== "All") rows = rows.filter((c) => c.format === formatFilter.toLowerCase());
    if (statusFilter !== "All") {
      const map: Record<string, CreativeAsset["status"]> = {
        Active: "active",
        Fatigued: "fatigued",
        Paused: "paused",
        "Top Performer": "top_performer",
      };
      rows = rows.filter((c) => c.status === map[statusFilter]);
    }
    const sorters: Record<string, (a: CreativeAsset, b: CreativeAsset) => number> = {
      ROAS: (a, b) => b.roas - a.roas,
      CTR: (a, b) => b.ctr - a.ctr,
      Spend: (a, b) => b.spend - a.spend,
      Age: (a, b) => b.ageDays - a.ageDays,
    };
    rows.sort(sorters[sort] ?? sorters.ROAS!);
    return rows;
  }, [formatFilter, statusFilter, sort]);

  return (
    <>
      <PageActions
        showExport={false}
        primaryAction={{ label: "Generate New Creative", onClick: () => setModalOpen(true), variant: "primary" }}
      />
      <div className="space-y-6 p-6">
        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
          {[
            { label: "Total Creatives", value: MOCK_CREATIVE_STATS.total },
            { label: "Top Performers (ROAS > 4x)", value: MOCK_CREATIVE_STATS.topPerformers },
            { label: "Fatigued (CTR declining)", value: MOCK_CREATIVE_STATS.fatigued },
            { label: "Generated by AI", value: MOCK_CREATIVE_STATS.aiGenerated },
          ].map((s) => (
            <div key={s.label} className="rounded-[var(--adpilot-radius-card)] border border-[var(--adpilot-border)] bg-[var(--adpilot-surface)] p-4">
              <p className="text-xs uppercase text-[var(--adpilot-text-muted)]">{s.label}</p>
              <p className="mt-2 text-2xl font-semibold">{s.value}</p>
            </div>
          ))}
        </div>

        <div className="flex flex-wrap items-center gap-4">
          <FilterChips options={["All", "Image", "Video", "Carousel"]} value={formatFilter} onChange={setFormatFilter} />
          <FilterChips
            label="Status"
            options={["All", "Active", "Fatigued", "Paused", "Top Performer"]}
            value={statusFilter}
            onChange={setStatusFilter}
          />
          <select
            value={sort}
            onChange={(e) => setSort(e.target.value)}
            className="rounded-[var(--adpilot-radius-item)] border border-[var(--adpilot-border)] px-3 py-1.5 text-sm"
          >
            {["ROAS", "CTR", "Spend", "Age"].map((o) => (
              <option key={o}>Sort: {o}</option>
            ))}
          </select>
        </div>

        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
          {filtered.map((c) => (
            <article
              key={c.id}
              className="group rounded-[var(--adpilot-radius-card)] border border-[var(--adpilot-border)] bg-[var(--adpilot-surface)] overflow-hidden"
            >
              <div
                className="flex h-36 items-end justify-between p-2"
                style={{ background: c.color }}
              >
                <Badge variant="muted">{c.format}</Badge>
                {c.aiGenerated ? <span className="text-xs">AI Generated</span> : null}
              </div>
              <div className="p-3">
                <p className="text-sm font-semibold text-[var(--adpilot-text-primary)]">{c.name}</p>
                <p className="mt-1 text-xs text-[var(--adpilot-text-muted)]">{c.campaignName}</p>
                <dl className="mt-2 grid grid-cols-2 gap-1 text-xs">
                  <div>
                    <dt className="text-[var(--adpilot-text-muted)]">ROAS</dt>
                    <dd className="font-medium">{c.roas.toFixed(1)}x</dd>
                  </div>
                  <div>
                    <dt className="text-[var(--adpilot-text-muted)]">CTR</dt>
                    <dd className="font-medium">{formatPercent(c.ctr, 1)}</dd>
                  </div>
                  <div>
                    <dt className="text-[var(--adpilot-text-muted)]">Spend</dt>
                    <dd className="font-medium">{formatCurrency(c.spend)}</dd>
                  </div>
                  <div>
                    <dt className="text-[var(--adpilot-text-muted)]">Impr.</dt>
                    <dd className="font-medium">{formatNumber(c.impressions)}</dd>
                  </div>
                </dl>
                <div className="mt-2 flex flex-wrap items-center gap-2">
                  {statusBadge(c.status)}
                  <span className="text-xs text-[var(--adpilot-text-muted)]">{c.ageDays} days</span>
                </div>
                <div className="mt-3 flex flex-wrap gap-1 opacity-100 sm:opacity-0 sm:transition-opacity sm:group-hover:opacity-100">
                  <AIInlineActionButton actionId="cr-variations" label="Generate variations" variant="secondary" className="!text-[10px]" />
                  <AIInlineActionButton actionId="cr-hooks" label="Explain why this worked" variant="ghost" className="!text-[10px]" />
                  {c.status === "fatigued" ? (
                    <AIInlineActionButton actionId="cr-fatigue" label="Replace fatigued" variant="ghost" className="!text-[10px]" />
                  ) : null}
                  {c.format === "video" ? (
                    <AIInlineActionButton actionId="cr-ugc" label="Create UGC script" variant="ghost" className="!text-[10px]" />
                  ) : null}
                </div>
              </div>
            </article>
          ))}
        </div>
      </div>

      <Modal open={modalOpen} onClose={() => setModalOpen(false)} title="Generate New Creative" wide>
        <form className="space-y-4" onSubmit={(e) => e.preventDefault()}>
          <label className="block text-sm">
            <span className="text-[var(--adpilot-text-muted)]">Describe the creative you want to generate...</span>
            <textarea
              className="mt-1 w-full rounded-[var(--adpilot-radius-item)] border border-[var(--adpilot-border)] p-2 text-sm"
              rows={3}
              placeholder="e.g. UGC-style testimonial for summer sale..."
            />
          </label>
          <label className="block text-sm">
            Style
            <select className="mt-1 w-full rounded-[var(--adpilot-radius-item)] border border-[var(--adpilot-border)] p-2 text-sm">
              {MOCK_CREATIVE_STYLES.map((s) => (
                <option key={s}>{s}</option>
              ))}
            </select>
          </label>
          <label className="block text-sm">
            Format
            <select className="mt-1 w-full rounded-[var(--adpilot-radius-item)] border border-[var(--adpilot-border)] p-2 text-sm">
              {(["image", "video", "carousel"] as CreativeFormat[]).map((f) => (
                <option key={f}>{f}</option>
              ))}
            </select>
          </label>
          <label className="block text-sm">
            Campaign
            <select className="mt-1 w-full rounded-[var(--adpilot-radius-item)] border border-[var(--adpilot-border)] p-2 text-sm">
              {MOCK_CAMPAIGN_OPTIONS.map((c) => (
                <option key={c}>{c}</option>
              ))}
            </select>
          </label>
          <label className="block text-sm">
            Reference creative (optional)
            <select className="mt-1 w-full rounded-[var(--adpilot-radius-item)] border border-[var(--adpilot-border)] p-2 text-sm">
              <option value="">None</option>
              {MOCK_CREATIVES.map((c) => (
                <option key={c.id} value={c.id}>
                  {c.name}
                </option>
              ))}
            </select>
          </label>
          <Button type="submit" variant="primary" className="w-full">
            Generate
          </Button>
          <p className="text-center text-xs text-[var(--adpilot-text-muted)]">
            Powered by Higgsfield AI — generation takes 60-90 seconds
          </p>
        </form>
      </Modal>
    </>
  );
}
